version: '3.7'

services:
  dockerd-exporter:
    image: ${IMAGE_NAME}:${IMAGE_TAG:-latest}
    environment:
      PORT:
      DOCKER_GWBRIDGE_IP:
      DOCKER_GWBRIDGE_PORT:
    networks:
      monitoring-net:
    volumes:
      - work-vol:/etc/.caddy
    configs:
      - source: caddyfile-config
        target: /etc/Caddyfile
    deploy:
      mode: global
      restart_policy:
        delay: ${RESTART_DELAY:-10s}
      update_config:
        delay: ${UPDATE_DELAY:-30s}
      resources:
        limits:
          cpus: '${RESOURCES_LIMITS_CPUS:-0.1}'
          memory: ${RESOURCES_LIMITS_MEMORY:-32M}
        reservations:
          cpus: '${RESOURCES_RESERVATIONS_CPUS:-0.001}'
          memory: ${RESOURCES_RESERVATIONS_MEMORY:-8M}

networks:
  monitoring-net:
    name: ${MONITORING_NET_NAME:-monitoring-net}
    driver: ${MONITORING_NET_DRIVER:-overlay}
    external: true

volumes:
  work-vol:
    name: ${WORK_VOL_NAME:-dockerd-exporter-work-vol}

configs:
  caddyfile-config:
    name: ${CADDYFILE_CONFIG_NAME:-dockerd-exporter-caddyfile}
    file: ./config/Caddyfile
